### ISSUE TITLE
Archivo .env

### ISSUE THREAD

**Issue by castromaciel** [LALedesma007/SmartPhone#29]
## Descripción

Como bien sabemos, en el archivo `.env` se almacenan las variables de entorno del proyecto. El mismo no debería ser publicado en el repositorio ya que puede incluir información sensible del proyecto. 

Por favor, [retirarlo](https://github.com/LALedesma007/SmartPhone/blame/1c9a82e277411c7119a93dc8efc2aeb5a28e8264/.env#L1) y realizar los ajustes necesarios (en caso de requerirlos)

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by LALedesma007** [comment]
Se eliminó del repositorio el archivo .env
