### ISSUE TITLE
Navegación - Boton Salir

### ISSUE THREAD

**Issue by castromaciel** [LALedesma007/SmartPhone#30]
## Proceso

1. Ingresar a la aplicación

## Resultado esperado

Cuando un usuario ingresa a una aplicación, que requiera inicio de sesión, el botón de **salir** o **cerrar sesión** no debería aparecer hasta que se haya iniciado sesión.

## Resultado actual

Aparece el boton **salir**, sin haber iniciado sesión.

## Captura

<img width="1395" alt="image" src="https://github.com/LALedesma007/SmartPhone/assets/83432755/9dc875ee-771d-4c7c-bc06-3162d4cbb63a">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by LALedesma007** [comment]
Se ha ocultado el boton salir
