### ISSUE TITLE
Tablet - Carrito de compras

### ISSUE THREAD

**Issue by castromaciel** [LALedesma007/SmartPhone#31]
## Proceso

1. Iniciar sesión
2. Agregar productos al carrito

## Resultado esperado

Se esperan ver los productos en forma de grilla y que la información de los mismos sea legible

## Resultado actual

Si bien, los productos se visualizan, el botón eliminar y el precio se desbordan de la card.

## Captura

<img width="577" alt="image" src="https://github.com/LALedesma007/SmartPhone/assets/83432755/c8e519f1-c5ec-449a-a565-88a64abc5c5b">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by LALedesma007** [comment]
Se ha corregido la visualización de los productos en el carrito
