### ISSUE TITLE
Registro - Nombres de usuarios repetidos

### ISSUE THREAD

**Issue by castromaciel** [LALedesma007/SmartPhone#32]
## Proceso

1. Ingresar a la pagina
2. Ir a registrar un usuario
3. Registrar un usuario
4. Registrar otro usuario, con un correo diferente, pero el mismo nombre de usuario.

## Resultado esperado

No debería permitir que dos usuarios tengan el mismo **nombre de usuario**.

## Resultado actual

Sale un mensaje de usuario registrado, cuando debería dar un error en la creación.

### Primer Usuario

```json
{
    "name": "Prueba",
    "lastName": "Prueba",
    "email": "prueba@prueba.com",
    "userName": "Prueba",
    "password": "Prueba1234"
}
```

<img width="1439" alt="image" src="https://github.com/LALedesma007/SmartPhone/assets/83432755/3cc88dba-31ba-4019-84c2-aea850afccda">

### Segundo usuario

```json
{
    "name": "Prueba",
    "lastName": "Prueba",
    "email": "segundaprueba@prueba.com",
    "userName": "Prueba",
    "password": "Prueba1234"
}
```

<img width="1440" alt="image" src="https://github.com/LALedesma007/SmartPhone/assets/83432755/74572656-3668-4f31-89f6-b60fbc435f57">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by LALedesma007** [comment]
Se ha corregido la duplicación del mismo nombre de usuario
