### ISSUE TITLE
Login - Inicio de sesión multiple

### ISSUE THREAD

**Issue by castromaciel** [LALedesma007/SmartPhone#33]
## Proceso

1. Iniciar Sesión
2. Abrir el menu
3. Permite el inicio de sesión nuevamente

## Resultado esperado

Cuando un usuario se Loggea, se espera que **No pueda registrar otro usuario**, ni tampoco **volver a loggearse**. Esto debido a que puede generar errores.

## Resultado actual

Se puede iniciar sesión, aunque ya nos hayamos loggeado.

## Captura

https://github.com/LALedesma007/SmartPhone/assets/83432755/fd49a863-6692-45b2-8f19-f36483ea0d9c

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by LALedesma007** [comment]
Se ha corregido el logueo, ahora cuando el usuario esta logueado los botones acceso y registro ya no aparecen
