### ISSUE TITLE
Login - Inicio de sesión con clave incorrecta

### ISSUE THREAD

**Issue by castromaciel** [LALedesma007/SmartPhone#34]
## Proceso

1. Ir al login
2. Diligenciar los campos de un usuario
3. Colocar una clave incorrecta

## Resultado esperado

Debería dar un error ya que la clave con la que se intenta ingresar es incorrecta

## Resultado actual

Inicia sesión sin validar la clave.

## Captura

<img width="323" alt="image" src="https://github.com/LALedesma007/SmartPhone/assets/83432755/2003cd34-ed2a-4f88-8c0c-5656c4cb84eb">
<img width="303" alt="image" src="https://github.com/LALedesma007/SmartPhone/assets/83432755/1a55858d-27cf-4a75-965d-e0b4ad8fa5a7">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by LALedesma007** [comment]
Se ha corregido la validación con la contraseña
