### ISSUE TITLE
Botones sin acción

### ISSUE THREAD

**Issue by castromaciel** [LALedesma007/SmartPhone#35]
## Proceso

1. Ingresar a la aplicación
2. Hacer click en los elementos de acción (botones, enlaces, inputs)

## Resultado esperado

Todos los elementos de este tipo, al interactuar deberían realizar una acción (si la función no está implementada, redirigir a una pagina 404)

## Resultado actual

Algunos elementos no realizan ninguna acción

### Terminos y condiciones
https://github.com/LALedesma007/SmartPhone/assets/83432755/151a4061-3937-4f86-a42c-ad911eb2d35e

### Logo
<img width="300" alt="image" src="https://github.com/LALedesma007/SmartPhone/assets/83432755/ebe4bb83-ba83-4bd0-8930-6a7d5955609c">

### Logo del footer
<img width="321" alt="image" src="https://github.com/LALedesma007/SmartPhone/assets/83432755/42bf7912-622e-4a81-94d3-3fb92d9df79a">

### Boton de comprar
<img width="323" alt="image" src="https://github.com/LALedesma007/SmartPhone/assets/83432755/965169a5-b80d-4552-9538-fdc93be8ef44">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by LALedesma007** [comment]
Se le agregaron acciones a los botones
