### ISSUE TITLE
Login - Validar clave

### ISSUE THREAD

**Issue by castromaciel** [LALedesma007/SmartPhone#36]
## Proceso

1. Iniciar en la pagina de Acceso
2. Diligenciar mal los campos

## Resultado esperado

Al diligenciar mal los datos de un formulario, por seguridad se debería informar que alguno de los campos es incorrencto, pero no especificar cual.

## Resultado actual

Se muestra un error no esperado.

## Captura

<img width="327" alt="image" src="https://github.com/LALedesma007/SmartPhone/assets/83432755/65e4fc48-7149-4e06-b26b-16c9188eeefb">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by LALedesma007** [comment]
Se ha corregido el mensaje de contraseña incorrecta
