### ISSUE TITLE
Herramientas de dessarrollo - Errores en consola

### ISSUE THREAD

**Issue by castromaciel** [LALedesma007/SmartPhone#37]
## Proceso

1. Iniciar en la página
2. Abrir las herramientaas de desarrollo
3. Verificar la Consola
4. Verificar el Storage

## Resultado esperado

La consola no debe mostrar errores inesperados o logs del codigo, mientras que en el storage NO se debe almacenar información sensible como la clave del usuario (aun si está encriptada).

## Resultado actual

Se precisan logs al realizar un registro.
Se almacena la contraseña en el storage.

### Consola
<img width="1316" alt="image" src="https://github.com/LALedesma007/SmartPhone/assets/83432755/d285c069-f4d3-45d8-95ff-fd233c89ab76">

### Local storage
<img width="711" alt="image" src="https://github.com/LALedesma007/SmartPhone/assets/83432755/fa873d0d-1d32-4aba-9097-711252139e82">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by LALedesma007** [comment]
Se ha corregido el log y la visualizacion de la contraseña en el localStorage
