### ISSUE TITLE
Mobile - Tamaño del iframe de youtube

### ISSUE THREAD

**Issue by castromaciel** [LALedesma007/SmartPhone#38]
## Proceso

1. Iniciar en la web
2. Hacer click en una imagen del carrousel

## Resultado esperado

Ver una previsualizacion completa de la imagen

## Resultado actual

Al ser pantallas pequeñas, no se visualiza todo el contenido

## Captura

<img width="322" alt="image" src="https://github.com/LALedesma007/SmartPhone/assets/83432755/d7c1ff10-bb8a-4192-9ba1-95971f51db8d">

<img width="325" alt="image" src="https://github.com/LALedesma007/SmartPhone/assets/83432755/b9f5350e-c83e-4e2e-94ae-29a4b5b6f367">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by LALedesma007** [comment]
Se ajustó el tamañao del video en dimensiones pequeñas
