### ISSUE TITLE
Admin - Crear/Editar usuario

### ISSUE THREAD

**Issue by castromaciel** [LALedesma007/SmartPhone#39]
## Proceso

1. Iniciar sesión con un usuario administrador
2. Dirigirse a la página Administrador
3. Dar click en 'Agregar nuevos usuarios'

## Resultado esperado

Se espera visualizar los campos de creación de un usuario.

## Resultado actual

Se visualizan algunos campos invertidos. Placeholder de los campos en editar incorrectos

### Agregar usuario
<img width="1440" alt="image" src="https://github.com/LALedesma007/SmartPhone/assets/83432755/abdf06ff-87b6-4c99-8cb7-3701ad5ff7b3">

### Editar usuario
<img width="1131" alt="image" src="https://github.com/LALedesma007/SmartPhone/assets/83432755/84e730cb-2235-49fb-8c8b-8990376fbf47">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by LALedesma007** [comment]
Se han corregido los placeholder
