### ISSUE TITLE
Admin - Tablas

### ISSUE THREAD

**Issue by castromaciel** [LALedesma007/SmartPhone#40]
## Proceso

1. Iniciar sesión con un usuario administrador
2. Dirigirse a la página Administrador

## Resultado esperado

No se deben mostrar las contraseñas en la tabla de administrador

## Resultado actual

Se muestran las claves

## Captura

<img width="1440" alt="image" src="https://github.com/LALedesma007/SmartPhone/assets/83432755/db1fd15f-4b4a-4b66-b8a7-43c742cf19e7">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by LALedesma007** [comment]
Se eliminaron la visualizaciones de las contraseñas del listado de usuarios registrados
