### ISSUE TITLE
Admin - Edicion de productos

### ISSUE THREAD

**Issue by castromaciel** [LALedesma007/SmartPhone#41]
## Proceso

1. Iniciar sesión con un usuario administrador
2. Dirigirse a la página Administrador
3. Dar click en Productos
4. Editar un producto

## Resultado esperado

En este caso, solo se desea editar el precio del producto. Por lo que al dar click en editar, se espera que los campos estén autocompletados y cambiar **únicamente el precio del producto** y guardar los cambios

## Resultado actual

Se pide diligenciar toda la información aun cuando se quiere realizar la modificación de un solo campo.

## Captura

<img width="979" alt="image" src="https://github.com/LALedesma007/SmartPhone/assets/83432755/086ae89d-904e-4ff2-b7f2-50b88a39d4e4">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by LALedesma007** [comment]
Se realizaron los cambios para la edicion de un solo campo
