### ISSUE TITLE
Admin - Imagen en el sidebar

### ISSUE THREAD

**Issue by castromaciel** [LALedesma007/SmartPhone#42]
## Proceso

1. Iniciar sesión
2. Dirigirse a admin
3. Visualizar el sidebar

## Resultado esperado

Se espera que las imagenes, en caso de no cargar correctamente, presenten un texto alternativo

## Resultado actual

La imagen no carga, y no tiene un texto alternativo

## Captura

<img width="1437" alt="image" src="https://github.com/LALedesma007/SmartPhone/assets/83432755/959e05d2-a056-47e7-9348-94e8dda7c785">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by LALedesma007** [comment]
Se ha corregido la imagen faltante y se agregaron los atributos alt a los elementos img
