### ISSUE TITLE
Admin - Administración

### ISSUE THREAD

**Issue by castromaciel** [LALedesma007/SmartPhone#43]
## Proceso

1. Ingresar con un usuario admin
2. Ir a administración
3. Se realizan multiples peticiones al servidor

## Resultado esperado

Todas las peticiones, en caso de traer información, no se deberían ejecutar multiples veces.

## Resultado actual

Se ejecutan multiples peticiones con solo ingresar a la app

## Captura

https://github.com/LALedesma007/SmartPhone/assets/83432755/14770c72-9f87-414b-b9b3-6454bb2c154e

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by LALedesma007** [comment]
Se ha corregido las muliples peticiones en el administrador
